-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-11-15 13:58:47 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE administrador (
    id_admin            CHAR(6) NOT NULL,
    nombre_admin        VARCHAR(50) NOT NULL,
    dni                 NUMERIC(9) NOT NULL,
    telef_admin         VARCHAR(12) NOT NULL,
    correo_admin        VARCHAR(50) NOT NULL,
    admin_user          VARCHAR(100) NOT NULL,
    admin_pass          VARCHAR(100) NOT NULL,
    admin_foto          VARCHAR(50) NOT NULL,
    clinica_id_clinica  CHAR(6) NOT NULL
);

ALTER TABLE administrador ADD CONSTRAINT administrador_pk PRIMARY KEY ( id_admin );

CREATE TABLE categoria (
    id_categoria      INTEGER NOT NULL,
    nombre_categoria  VARCHAR(50) NOT NULL
);

ALTER TABLE categoria ADD CONSTRAINT categoria_pk PRIMARY KEY ( id_categoria );

CREATE TABLE cliente (
    id_cliente         INTEGER NOT NULL IDENTITY(1,1),
    nombres_cliente    VARCHAR(50) NOT NULL,
    apellidos_cliente  VARCHAR(50) NOT NULL,
    dni                NUMERIC(9) NOT NULL,
    telef_cliente      VARCHAR(12) NOT NULL,
    correo_cliente     VARCHAR(50) NOT NULL,
    cliente_user       VARCHAR(100) NOT NULL UNIQUE,
    cliente_pass       VARCHAR(100) NOT NULL,
    cliente_foto       VARCHAR(200) NOT NULL,
    fecha_nacimiento   DATE NOT NULL,
    seguro             VARCHAR(60) NOT NULL,
    edad               INTEGER NOT NULL
);

ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY ( id_cliente );

CREATE TABLE clinica (
    id_clinica         CHAR(6) NOT NULL,
    ruc                NUMERIC(11) NOT NULL,
    nombre_clinica     VARCHAR(40) NOT NULL,
    direccion_clinica  VARCHAR(50) NOT NULL,
    telef_general1     VARCHAR(12) NOT NULL,
    telef_general2     VARCHAR(12) NOT NULL,
    horario_barberia   VARCHAR(50) NOT NULL
);

ALTER TABLE clinica ADD CONSTRAINT clinica_pk PRIMARY KEY ( id_clinica );

CREATE TABLE doctor (
    id_doctor           CHAR(6) NOT NULL,
    nombre_doctor       VARCHAR(50) NOT NULL,
    dni                 NUMERIC(9) NOT NULL,
    telef_doc           VARCHAR(12) NOT NULL,
    correo_doc          VARCHAR(50) NOT NULL,
    doc_user            VARCHAR(100) NOT NULL,
    doc_pass            VARCHAR(100) NOT NULL,
    doc_foto            VARCHAR(50) NOT NULL,
    clinica_id_clinica  CHAR(6) NOT NULL,
    horario_id_horario  CHAR(6) NOT NULL,
    id_especialidad     CHAR(6) NOT NULL
);

ALTER TABLE doctor ADD CONSTRAINT doctor_pk PRIMARY KEY ( id_doctor );

CREATE TABLE emple_emergencia (
    id_empemer          CHAR(6) NOT NULL,
    nombre_emple        VARCHAR(50) NOT NULL,
    dni                 NUMERIC(9) NOT NULL,
    telef_emple         VARCHAR(12) NOT NULL,
    correo_emple        VARCHAR(50) NOT NULL,
    emer_user           VARCHAR(100) NOT NULL,
    emer_pass           VARCHAR(100) NOT NULL,
    emer_foto           VARCHAR(50) NOT NULL,
    clinica_id_clinica  CHAR(6) NOT NULL,
    id_sector           CHAR(6) NOT NULL
);

CREATE TABLE especialidad (
    id_especialidad  CHAR(6) NOT NULL,
    nombre_esp       VARCHAR(50) NOT NULL,
    descripcion      VARCHAR(100) NOT NULL
);

ALTER TABLE especialidad ADD CONSTRAINT especialidad_pk PRIMARY KEY ( id_especialidad );

CREATE TABLE horario (
    id_horario   CHAR(6) NOT NULL,
    hora_inicio  VARCHAR(30) NOT NULL,
    hora_fin     VARCHAR(30) NOT NULL,
    dia1         VARCHAR(30) NOT NULL,
    dia2         VARCHAR(30) NOT NULL,
    dia3         VARCHAR(30) NOT NULL,
    dia4         VARCHAR(30) NOT NULL,
    dia5         VARCHAR(30) NOT NULL,
    dia6         VARCHAR(30) NOT NULL
);

ALTER TABLE horario ADD CONSTRAINT horario_pk PRIMARY KEY ( id_horario );

CREATE TABLE medicina (
    id_medicina         CHAR(6) NOT NULL,
    nombre_medicina     VARCHAR(50) NOT NULL,
    receta_medica       CHAR(1) NOT NULL,
    cantidad            INTEGER NOT NULL,
    precio              NUMERIC(5, 2) NOT NULL,
    id_tipomedicina     INTEGER NOT NULL,
    clinica_id_clinica  CHAR(6) NOT NULL
);

ALTER TABLE medicina ADD CONSTRAINT medicina_pk PRIMARY KEY ( id_medicina );

CREATE TABLE reserva (
    id_reserva          INTEGER NOT NULL IDENTITY(1,1),
    fecha_reserva       DATE NOT NULL,
    hora                VARCHAR(30) NOT NULL,
    doctor_id_doctor    CHAR(6) NOT NULL,
    cliente_id_cliente  INTEGER NOT NULL,
    id_servicio         CHAR(6) NOT NULL
);

ALTER TABLE reserva ADD CONSTRAINT reserva_pk PRIMARY KEY ( id_reserva );

CREATE TABLE sector_emergencia (
    id_sector      CHAR(6) NOT NULL,
    nombre_sector  VARCHAR(50) NOT NULL
);

ALTER TABLE sector_emergencia ADD CONSTRAINT sector_emergencia_pk PRIMARY KEY ( id_sector );

CREATE TABLE servicio_doctor (
    doctor_id_doctor  CHAR(6) NOT NULL,
    id_servicio       CHAR(6) NOT NULL
);

CREATE TABLE servicio_especialidad (
    id_servicio             CHAR(6) NOT NULL,
    nombre_esp              VARCHAR(50) NOT NULL,
    precio                  NUMERIC(4, 2) NOT NULL,
    categoria_id_categoria  INTEGER NOT NULL
);

ALTER TABLE servicio_especialidad ADD CONSTRAINT servicio_especialidad_pk PRIMARY KEY ( id_servicio );

CREATE TABLE tipo_medicina (
    id_tipomedicina  INTEGER NOT NULL,
    caracterisitica  VARCHAR(100) NOT NULL
);

ALTER TABLE tipo_medicina ADD CONSTRAINT tipo_medicina_pk PRIMARY KEY ( id_tipomedicina );

ALTER TABLE administrador
    ADD CONSTRAINT administrador_clinica_fk FOREIGN KEY ( clinica_id_clinica )
        REFERENCES clinica ( id_clinica );

ALTER TABLE servicio_especialidad
    ADD CONSTRAINT categoria_fk FOREIGN KEY ( categoria_id_categoria )
        REFERENCES categoria ( id_categoria );

ALTER TABLE doctor
    ADD CONSTRAINT doctor_clinica_fk FOREIGN KEY ( clinica_id_clinica )
        REFERENCES clinica ( id_clinica );

ALTER TABLE doctor
    ADD CONSTRAINT doctor_especialidad_fk FOREIGN KEY ( id_especialidad )
        REFERENCES especialidad ( id_especialidad );

ALTER TABLE doctor
    ADD CONSTRAINT doctor_horario_fk FOREIGN KEY ( horario_id_horario )
        REFERENCES horario ( id_horario );

ALTER TABLE emple_emergencia
    ADD CONSTRAINT emple_emergencia_clinica_fk FOREIGN KEY ( clinica_id_clinica )
        REFERENCES clinica ( id_clinica );

ALTER TABLE medicina
    ADD CONSTRAINT medicina_clinica_fk FOREIGN KEY ( clinica_id_clinica )
        REFERENCES clinica ( id_clinica );

ALTER TABLE medicina
    ADD CONSTRAINT medicina_tipo_medicina_fk FOREIGN KEY ( id_tipomedicina )
        REFERENCES tipo_medicina ( id_tipomedicina );

ALTER TABLE reserva
    ADD CONSTRAINT reserva_cliente_fk FOREIGN KEY ( cliente_id_cliente )
        REFERENCES cliente ( id_cliente );

ALTER TABLE reserva
    ADD CONSTRAINT reserva_doctor_fk FOREIGN KEY ( doctor_id_doctor )
        REFERENCES doctor ( id_doctor );

ALTER TABLE emple_emergencia
    ADD CONSTRAINT sector_emergencia_fk FOREIGN KEY ( id_sector )
        REFERENCES sector_emergencia ( id_sector );

ALTER TABLE servicio_doctor
    ADD CONSTRAINT servicio_doctor_doctor_fk FOREIGN KEY ( doctor_id_doctor )
        REFERENCES doctor ( id_doctor );

ALTER TABLE reserva
    ADD CONSTRAINT servicio_especialidad_fk FOREIGN KEY ( id_servicio )
        REFERENCES servicio_especialidad ( id_servicio );

ALTER TABLE servicio_doctor
    ADD CONSTRAINT servicio_especialidad_fkv1 FOREIGN KEY ( id_servicio )
        REFERENCES servicio_especialidad ( id_servicio );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0